### ISSUE TITLE
[BUG] Google Translator and Russian translation

### ISSUE THREAD

**Issue by Vladonai** [SillyTavern/SillyTavern#2681]
### Environment

🪟 Windows

### System

Microsoft Edge 127.0.2651.105

### Version

SillyTavern 1.12.4 'release' (6c0630e5)

### Desktop Information

Node.js version v20.12.0
KoboldCpp
Any models

### Describe the problem

When I use the Google Translator extension to translate, sometimes two unreadable characters are output instead of the Russian character (see screenshots). This happens irregularly, but consistently. The problem is very old.

### Additional info

![111](https://github.com/user-attachments/assets/67b69c09-2015-467a-ba66-e00f458feeb3)
![222](https://github.com/user-attachments/assets/d7f50e4d-9d35-4e91-9db8-c14a35818aaa)
![333](https://github.com/user-attachments/assets/b2719ee0-a758-4d56-a6b6-700c725ad385)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
This was fixed today on staging. Switch and check.

https://github.com/SillyTavern/SillyTavern/commit/ded26f978399f66f3ca50424089d923e7dd8171d

**Comment by Vladonai** [comment]
> This was fixed today on staging. Switch and check.
> 
> [ded26f9](https://github.com/SillyTavern/SillyTavern/commit/ded26f978399f66f3ca50424089d923e7dd8171d)

I've generated quite a bit of text and it looks like the problem is fixed.

**Comment by Cohee1207** [comment]
Reopen if persists.

**Comment by Vladonai** [comment]
Unfortunately the problem remains in SillyTavern 1.12.4 'release' (6c0630e5)

Now it occurs much (much) less often, but sometimes it slips through.

**Comment by Wolfsblvt** [comment]
It was fixed on **staging**, as Cohee said. It is not part of the release branch yet. That'll happen with the next official release.
